In [9]:
import os
import pybullet as p
import time
import pybullet_data
from xacrodoc import XacroDoc
import torch
import random
import matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import torch.optim as optim
import numpy as np
from pathlib import Path
from pybullet_utils import bullet_client as bc
import msgspec.json
import json
from pathlib import Path
from modules.data_processing import *
import torch.nn as nn
from collections import namedtuple, deque
from itertools import permutations, combinations, product

In [6]:
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()
print(input, target, output)

tensor([[-0.4952,  0.1120,  0.2871,  0.7519, -1.0368],
        [-0.0768,  1.4098, -0.0853, -0.7040,  1.1933],
        [ 0.2973, -1.2098, -1.1105, -0.1212,  0.8836]], requires_grad=True) tensor([[ 0.0586, -0.8121, -1.1115,  1.7081, -0.3816],
        [-0.9901,  0.2155, -1.2448, -1.7176, -0.9801],
        [-0.9541, -0.3532,  0.5688,  0.6326,  1.0979]]) tensor(1.3034, grad_fn=<MseLossBackward0>)


In [ ]:
learning_rate=1
class NeuralNetwork(nn.Module):
        def __init__(self, name, num_states, num_actions, ):
            super().__init__()
            self.name=name
            self.linear_relu_stack=nn.Sequential(
                nn.Linear(num_states, 128),
                nn.ReLU(),
                nn.Linear(128, 128),
                nn.ReLU(),
                nn.Linear(128, num_actions),
            )

        def forward(self, x):
            x = self.linear_relu_stack(x.float())
            return x, torch.argmax(x).int()
        
        def save(self, dir: str):
            torch.save(self.state_dict(), f'{dir}/{self.name}.pth')

optim = torch.optim.SGD(lr=learning_rate)    
            
test = NeuralNetwork("test", 4, 3)
print(test)
test(torch.tensor([0, 0, 0, 1]))

NeuralNetwork(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=4, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=3, bias=True)
  )
)


(tensor([0.0201, 0.0065, 0.0098], grad_fn=<ViewBackward0>),
 tensor(0, dtype=torch.int32))

In [ ]:
logits = model(x)          # shape: (batch, num_classes)
probs  = logits.softmax(1) # shape: (batch, num_classes)

labels = torch.tensor([2, 0, 1]).unsqueeze(1)  # shape: (batch, 1)

correct_probs = probs.gather(dim=1, index=labels)  # shape: (batch, 1)

In [5]:
test=torch.full((1,4), 1)
test

tensor([[1, 1, 1, 1]])

In [11]:
with open("Basic_Walking\replay_mems\X0zJxgdPRXaYj1Eq.pkl", 'wb') as f:
        print (pickle.load(f))

<>:1: SyntaxWarning: "\X" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\X"? A raw string is also an option.
<>:1: SyntaxWarning: "\X" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\X"? A raw string is also an option.
C:\Users\Chad Jorgenssen\AppData\Local\Temp\ipykernel_106728\2168801440.py:1: SyntaxWarning: "\X" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\X"? A raw string is also an option.
  with open("Basic_Walking\replay_mems\X0zJxgdPRXaYj1Eq.pkl", 'wb') as f:
C:\Users\Chad Jorgenssen\AppData\Local\Temp\ipykernel_106728\2168801440.py:1: SyntaxWarning: "\X" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\X"? A raw string is also an option.
  with open("Basic_Walking\replay_mems\X0zJxgdPRXaYj1Eq.pkl", 'wb') as f:


OSError: [Errno 22] Invalid argument: 'Basic_Walking\replay_mems\\X0zJxgdPRXaYj1Eq.pkl'

In [ ]:
int(time.time())

1773714898

: 